name: myst-deploy

on:
  push:
    branches: [main, master]
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.12"
      working-directory:
        required: false
        type: string
        default: .
      publish-dir:
        required: false
        type: string
        default: ./_build/html

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: pip install mystmd
      - name: Build the site
        run: myst build --html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ inputs.publish-dir }}
